sudo: required
language: go

go:
  - 1.6.x
  - 1.7.x
  - tip

cache:
  directories:
    - vendor
    - ${HOME}/.glide

before_install:
  - mkdir -p $GOPATH/bin
  - curl https://glide.sh/get | sh
  - sudo useradd -m -d /home/drone-scp -s /bin/bash drone-scp
  - sudo mkdir -p /home/drone-scp/.ssh
  - sudo chmod 700 /home/drone-scp/.ssh
  - sudo cp tests/.ssh/id_rsa.pub /home/drone-scp/.ssh/authorized_keys
  - sudo chown -R drone-scp /home/drone-scp/.ssh
  - mkdir -p ${HOME}/.ssh
  - chmod 700 ${HOME}/.ssh
  - cp -r tests/.ssh/id_rsa.pub tests/.ssh/id_rsa ${HOME}/.ssh/

install:
  - make dep_install

script:
  - make vet
  - make lint
  - make test
  - make build
